//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ServicioOperaciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioOperaciones.IOperaciones2")]
    public interface IOperaciones2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones2/Suma", ReplyAction="http://tempuri.org/IOperaciones2/SumaResponse")]
        int Suma(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones2/Suma", ReplyAction="http://tempuri.org/IOperaciones2/SumaResponse")]
        System.Threading.Tasks.Task<int> SumaAsync(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones2/Resta", ReplyAction="http://tempuri.org/IOperaciones2/RestaResponse")]
        int Resta(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones2/Resta", ReplyAction="http://tempuri.org/IOperaciones2/RestaResponse")]
        System.Threading.Tasks.Task<int> RestaAsync(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones2/Multiplicacion", ReplyAction="http://tempuri.org/IOperaciones2/MultiplicacionResponse")]
        int Multiplicacion(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones2/Multiplicacion", ReplyAction="http://tempuri.org/IOperaciones2/MultiplicacionResponse")]
        System.Threading.Tasks.Task<int> MultiplicacionAsync(int Numero1, int Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones2/Division", ReplyAction="http://tempuri.org/IOperaciones2/DivisionResponse")]
        decimal Division(decimal Numero1, decimal Numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones2/Division", ReplyAction="http://tempuri.org/IOperaciones2/DivisionResponse")]
        System.Threading.Tasks.Task<decimal> DivisionAsync(decimal Numero1, decimal Numero2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperaciones2Channel : PL.ServicioOperaciones.IOperaciones2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Operaciones2Client : System.ServiceModel.ClientBase<PL.ServicioOperaciones.IOperaciones2>, PL.ServicioOperaciones.IOperaciones2 {
        
        public Operaciones2Client() {
        }
        
        public Operaciones2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Operaciones2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Operaciones2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Operaciones2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Suma(int Numero1, int Numero2) {
            return base.Channel.Suma(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<int> SumaAsync(int Numero1, int Numero2) {
            return base.Channel.SumaAsync(Numero1, Numero2);
        }
        
        public int Resta(int Numero1, int Numero2) {
            return base.Channel.Resta(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<int> RestaAsync(int Numero1, int Numero2) {
            return base.Channel.RestaAsync(Numero1, Numero2);
        }
        
        public int Multiplicacion(int Numero1, int Numero2) {
            return base.Channel.Multiplicacion(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicacionAsync(int Numero1, int Numero2) {
            return base.Channel.MultiplicacionAsync(Numero1, Numero2);
        }
        
        public decimal Division(decimal Numero1, decimal Numero2) {
            return base.Channel.Division(Numero1, Numero2);
        }
        
        public System.Threading.Tasks.Task<decimal> DivisionAsync(decimal Numero1, decimal Numero2) {
            return base.Channel.DivisionAsync(Numero1, Numero2);
        }
    }
}
